# Setup
title:            café ascii
tagline:          'Studentisches Café im Informatikbau'
description:      'Das Studicafé in der Informatikfakultät'
url:              https://laikq.github.io
baseurl:          /ascii-dresden/

# Permalinks
permalink:        pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .envrc
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - flake.nix
  - flake.lock
  - shell.nix

author:
  name:           'John Doe'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
